spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
   level:
      org.springframework.data.mongodb: DEBUG
      org.mongodb.driver: DEBUG
      org.mongodb.driver.protocol.command: DEBUG  # shows insert commands
      org.mongodb.driver.cluster: OFF             # hides heartbeat noise



